version: '3.8'

services:
    crdb-1:
        container_name: crdb-1
        image: cockroachdb/cockroach:v23.1.14
        hostname: crdb-1
        environment:
            - COCKROACH_USER=admin
            - COCKROACH_PASSWORD=password
        ports:
            - "26257:26257"
            - "9080:9080"
        command: start --insecure --join=crdb-1,crdb-2
        volumes:
            - cockroach-volume-1:/cockroach/cockroach-data
        networks:
            - network_cockroachdb

    crdb-2:
        container_name: crdb-2
        image: cockroachdb/cockroach:v23.1.14
        hostname: crdb-2
        environment:
            - COCKROACH_USER=admin
            - COCKROACH_PASSWORD=password
        ports:
            - "26258:26258"
            - "9081:9081"
        command: start --insecure --join=crdb-1,crdb-2
        volumes:
            - cockroach-volume-2:/cockroach/cockroach-data
        networks:
            - network_cockroachdb

    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - network_spring

    tweet-service:
        container_name: tweet-service-container
        image: xsakon/tweet-service-image:latest
        ports:
            - "8081:8081"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        networks:
            - network_cockroachdb
            - network_spring
        depends_on:
            - crdb-2

    feed-service:
        container_name: feed-service-container
        image: xsakon/feed-service-image:latest
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        networks:
            - network_spring
        depends_on:
            - crdb-2
            - rabbitmq

    bot-service:
        container_name: bot-service-container
        image: xsakon/bot-service-image:latest
        ports:
            - "8082:8082"
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        networks:
            - network_spring

networks:
    network_cockroachdb:
        driver: bridge
    network_spring:
        driver: bridge

volumes:
    cockroach-volume-1:
    cockroach-volume-2: