server:
    port: 8081

spring:
    application:
        name: tweet
    datasource:
        url: jdbc:postgresql://localhost:26257/twt_feed_db
        username: admin
        password: password
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                jdbc:
                    lob:
                        #fix connection
                        non_contextual_creation: true
    rabbitmq:
        addresses: localhost:5672

rabbitmq:
    exchange: tweet.exchange
    routing-key: tweet.routing.key